version: '3'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: chatuser
      POSTGRES_PASSWORD: chatpass
      POSTGRES_DB: chatdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatuser -d chatdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "5432:5432"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV: production
      PORT: 8080
      DB_CONNECTION: "postgres://chatuser:chatpass@postgres:5432/chatdb?sslmode=disable"
      MAX_MESSAGE_SIZE: ${MAX_MESSAGE_SIZE:-4096}
      READ_TIMEOUT: ${READ_TIMEOUT:-60}
      WRITE_TIMEOUT: ${WRITE_TIMEOUT:-60}
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: 